### ISSUE TITLE
Capturing raw JSON output

### ISSUE THREAD

**Issue by biodtl916** [textkernel/tx-dotnet#20]
I am attempting to store the raw JSON response from a resume parsing using the SDK. I am using the basic example of:

ParseRequest request = new ParseRequest(doc, new ParseOptions());

When examining the SkillsData output in response.Value.ResumeData I am not seeing the values for ID, Name, or PercentOfOverall. The same is happening when looking at the SubTaxonomies. This data is all present when looking at the SkillsData = List<Sovren.Models.Resume.Skills.ResumeTaxonomyRoot> in the response. Is this by design? The information is also displayed when using the demo parser on the Sovren website.

Thank you.

**Comment by sovren-jwesson** [comment]
First of all, thanks for submitting our first GitHub issue!

Can you post an example of the JSON output? I am not able to repro this issue. Also, how are you generating the JSON? You should be using `response.Value.ResumeData.ToJson()` to ensure that the proper JSON converters are used.

Thanks.

**Comment by biodtl916** [comment]
Thank you for the quick response! It turns out that I was mistakenly expecting the same format and order of the JSON output on the demo site and the SDK. I am now seeing the other values, they were not listed at the bottom of the node and I had missed them.

Thank you again for creating this repo!
