### ISSUE TITLE
easyAccess?.GetPhoneNumbers() - System.ArgumentNullException: 'Value cannot be null. (Parameter 'source')' 

### ISSUE THREAD

**Issue by wassim-azi** [textkernel/tx-dotnet#25]
Hello,

`
_profile.PhoneNumber = easyAccess?.GetPhoneNumbers()?.FirstOrDefault()
`
Is throwing an error of type **Value cannot be null. (Parameter 'source')**

![image](https://user-images.githubusercontent.com/670586/125430313-96f93a01-00bb-4af4-ae3b-2fe1c4d9b24c.png)

**Comment by sovren-jwesson** [comment]
@wassim-azirar thanks for reporting this issue. It has been fixed in v1.1.1 which is now available on NuGet.
